#pragma once

#include "NativeGameplayTags.h"

namespace ActionCombatLyraBridgeTags
{
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_Dash);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_State_Dodge);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_State_Dodge_IFrame);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_State_Guard);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_State_ForcedGuard);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_State_GuardBroken);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_GameplayEvent_GuardBlocked);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combat_GameplayEvent_GuardBroken);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_DamageMultiplier);
    ACTIONCOMBATLYRABRIDGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_GuardDamage);
}
